name: Deploy new version

on:
  push:

env:
  APP_NAME: PicoBackingtracksTransport

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pico-builder-image .

      - name: Create Docker container
        run: docker create --name pico-builder-container pico-builder-image

      - name: Copy out .uf2 file
        run: docker cp pico-builder-container:/project/src/build/${APP_NAME}.uf2 ./${APP_NAME}.uf2

      - name: Create and push a new tag
        run: |
          NEWTAG="v$(date +'%Y%m%d%H%M%S')"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$NEWTAG"
          git push origin "$NEWTAG"

      - name: Debug Git State
        run: |
          git remote -v
          git branch -a
          git log --oneline

      - name: Verify pushed tags
        run: git tag

      - name: Wait for tag propagation
        run: sleep 15

      #- name: test push
        #run: 
          #git config user.name "GitHub Actions"
          #git config user.email "github-actions@users.noreply.github.com"
          #git tag $NEWTAG
          #git push origin $NEWTAG
        #with:
          #files: ${{ env.app_name }}.uf2

      - name: Push to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: $NEWTAG
          files: ${{ env.app_name }}.uf2