name: Deploy new version

on:
  push:

env:
  APP_NAME: PicoBackingtracksTransport

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pico-builder-image .

      - name: Create Docker container
        run: docker create --name pico-builder-container pico-builder-image

      - name: Copy out .uf2 file
        run: docker cp pico-builder-container:/project/src/build/${APP_NAME}.uf2 ./${APP_NAME}.uf2

      - name: Put environment variable into the env context
        run: echo "app_name=$APP_NAME" >> $GITHUB_ENV

      - name: Push to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.app_name }}.uf2